name: "blockscout-explorer"
version: '3.9'

services:
  redis_db:
    extends:
      file: ./services/redis.yml
      service: redis_db
    networks:
    - project-eth-cc-group-1_chainnet

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    networks:
    - project-eth-cc-group-1_chainnet
    
  db:
    extends:
      file: ./services/db.yml
      service: db
    networks:
        - project-eth-cc-group-1_chainnet
  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
    networks:
    - project-eth-cc-group-1_chainnet

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
    - project-eth-cc-group-1_chainnet

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
    - project-eth-cc-group-1_chainnet

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    networks:
    - project-eth-cc-group-1_chainnet

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    networks:
    - project-eth-cc-group-1_chainnet

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/stats.yml
      service: stats-db
    networks:
    - project-eth-cc-group-1_chainnet

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
    - project-eth-cc-group-1_chainnet

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
    - project-eth-cc-group-1_chainnet

networks:
  project-eth-cc-group-1_chainnet:
    external: true