name: "proyecto-eth-cc-groupo-1"
services:
  bootnode:
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./private_network:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    ports:
      - 8545:8545
    command:
      - -c
      - /scripts/create_directories_nodes.sh -b 1 -v 2 -n 2 -p 30305 -i 172.26.0.100 && /scripts/execute_bootnode.sh -h 8545 -i 172.26.0.100
      
    networks:
      chainnet:
        ipv4_address: 172.26.0.100

  node_validator_1:
    image: ethereum/client-go
    volumes:
      - ./private_network/validator_node_1:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/execute_validator_node.sh -p 8545
    networks:
      chainnet:
        ipv4_address: 172.26.0.101
  
  node_validator_2:
    image: ethereum/client-go
    volumes:
      - ./private_network/validator_node_2:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/execute_validator_node.sh -p 8545
    networks:
      chainnet:
        ipv4_address: 172.26.0.102

  node_2:
    image: ethereum/client-go
    volumes:
      - ./private_network/normal_node_1:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/execute_normal_node.sh -p 8545
    networks:
      chainnet:
        ipv4_address: 172.26.0.103

  node_3:
    image: ethereum/client-go
    volumes:
      - ./private_network/normal_node_2:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/execute_normal_node.sh -p 8545
    networks:
      chainnet:
        ipv4_address: 172.26.0.104

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
