services:
  bootnode:
    image: ethereum/client-go:alltools-latest
    volumes: 
      - ./private_network:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/crear_directorios.sh -n 3 -p 30305 -i 172.25.0.100
    networks:
      chainnet: 
        ipv4_address: 172.25.0.100
  
  node_1:
    image: ethereum/client-go
    volumes: 
      - ./private_network/node_1:/root/.ethereum
      - ./files_network:/scripts
    ports:
      - 8578:8578
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/ejecutar_nodo_validador.sh -p 8578
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101

  node_2:
    image: ethereum/client-go
    volumes: 
      - ./private_network/node_2:/root/.ethereum
      - ./files_network:/scripts
    ports:
      - 8545:8545
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/ejecutar_nodo_normal.sh -p 8545
    networks:
      chainnet: 
        ipv4_address: 172.25.0.102
  
  node_3:
    image: ethereum/client-go
    volumes: 
      - ./private_network/node_3:/root/.ethereum
      - ./files_network:/scripts
    ports:
      - 8580:8580
    entrypoint: bin/sh
    command:
      - -c
      - /scripts/ejecutar_nodo_normal.sh -p 8580
    networks:
      chainnet: 
        ipv4_address: 172.25.0.103

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24