name: private_network_1
services:
  bootnode:
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./private_network_1:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    ports:
      - '8545:8545'
    command:
      - '-c'
      - >-
        /scripts/create_directories_nodes.sh -b 1 -v 3 -n 2 -p 30305 &&
        /scripts/execute_bootnode.sh -h 8545
  node_validator_1:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/validator_node_1:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_validator_node.sh -p 8545
  node_validator_2:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/validator_node_2:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_validator_node.sh -p 8545
  node_validator_3:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/validator_node_3:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_validator_node.sh -p 8545
  node_normal_1:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/normal_node_1:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_normal_node.sh -p 8545
  node_normal_2:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/normal_node_2:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_normal_node.sh -p 8545
  redis_db:
    extends:
      file: ./explorer/services/redis.yml
      service: redis_db
  db-init:
    extends:
      file: ./explorer/services/db.yml
      service: db-init
  db:
    extends:
      file: ./explorer/services/db.yml
      service: db
  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./explorer/services/backend.yml
      service: backend
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      BLOCK_TRANSFORMER: clique
  visualizer:
    extends:
      file: ./explorer/services/visualizer.yml
      service: visualizer
  sig-provider:
    extends:
      file: ./explorer/services/sig-provider.yml
      service: sig-provider
  frontend:
    depends_on:
      - backend
    extends:
      file: ./explorer/services/frontend.yml
      service: frontend
  stats-db-init:
    extends:
      file: ./explorer/services/stats.yml
      service: stats-db-init
  stats-db:
    depends_on:
      - backend
    extends:
      file: ./explorer/services/stats.yml
      service: stats-db
  stats:
    depends_on:
      - stats-db
    extends:
      file: ./explorer/services/stats.yml
      service: stats
  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./explorer/services/nginx.yml
      service: proxy
  prueba_contenedor:
    image: ethereum/client-go
    volumes:
      - ./private_network_1/prueba_contenedor:/root/.ethereum
      - ./files_network:/scripts
    entrypoint: bin/sh
    command:
      - '-c'
      - /scripts/execute_normal_node.sh -p 8545
